[package]
name = "invasion_by_nightfall"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_turborand = "0.8.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
